SWC-5431
Sage-Bionetworks/SynapseWebClient pull request #4529
Opened 2021-03-03 18:06 UTC by jay-hodgson

2021-03-03 18:07 UTC, jay-hodgson commented on src/main/java/org/sagebionetworks/web/client/PortalGinInjector.java
> +	JSONListCellEditor createJSONListCellEditor();
Renamed injector method to be more clear (since we have a ListCellEditor as well)

2021-03-03 18:08 UTC, jay-hodgson commented on src/main/java/org/sagebionetworks/web/client/widget/table/v2/results/cell/EnumFormCellEditor.java
> +		if (validValues.size() > MAX_RADIO_BUTTONS) {
If configured with more than MAX_RADIO_BUTTONS items, then it uses a dropdown list view.  Otherwise, it uses the old radio buttons.

2021-03-03 18:09 UTC, jay-hodgson commented on src/test/java/org/sagebionetworks/web/unitclient/widget/table/v2/results/cell/EnumFormCellEditorImplTest.java
> +	private List<String> getValuesForDropdownList() {
Helper method, generates MAX_RADIO_BUTTONS + 1 values (to trigger the dropdown list renderer)

2021-03-04 22:11 UTC, zimingd requested changes
Logic looks great. `IntegerCellEditorView` just needs to be renamed to something less ambiguous.

2021-03-04 22:11 UTC, zimingd commented on src/main/java/org/sagebionetworks/web/client/widget/table/v2/results/cell/IntegerCellEditorView.java
> +public interface IntegerCellEditorView extends IsWidget, TakesValue<Integer>, HasKeyDownHandlers, Focusable {
When I see `IntegerCellEditorView`, I immediately think of an input box allowing only integer values.

I would describe this as a `ListIndexSelectionCellEditorView`? Or maybe `ListIndexChoiceCellEditorView` if `Selection` seems to imply the HTML `<select/>` tag?

2021-03-04 22:20 UTC, jay-hodgson commented on src/main/java/org/sagebionetworks/web/client/widget/table/v2/results/cell/IntegerCellEditorView.java
> +public interface IntegerCellEditorView extends IsWidget, TakesValue<Integer>, HasKeyDownHandlers, Focusable {
That's fair, renamed to `ListIndexSelectionCellEditorView`

2021-03-04 22:21 UTC, zimingd approved these changes

2021-03-04 22:24 UTC, merged